version: "3.7"
services:
  db:
    image: postgres:9.5.3
    restart: always
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: timhabermaas/cubemania_nginx
    restart: always
    depends_on:
      - records
      - web
      - backup
  records:
    build:
      context: ./records
      dockerfile: Dockerfile
    image: timhabermaas/cubemania_records
    restart: always
    environment:
      RUST_LOG: info
      RUST_BACKTRACE: 1
      HMAC_SECRET: ${HMAC_SECRET}
      DATABASE_URL: postgresql://postgres@db/cubemania_production
    depends_on:
      - db
  records-build:
    build:
      context: ./records
      dockerfile: Dockerfile
      target: builder
    depends_on:
      - db
    volumes:
      - ./records:/home/rust/src/records
  web:
    build: .
    image: timhabermaas/cubemania_rails
    restart: always
    command: bundle exec unicorn -p 3000 -c ./config/unicorn.rb
    volumes:
      - .:/cubemania
    depends_on:
      - db
      - cache
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://postgres@db/cubemania_production
      HMAC_SECRET: ${HMAC_SECRET}

  cache:
    image: memcached:alpine
    restart: always
    command: memcached -m 64

  backup:
    build:
      context: backup
      dockerfile: Dockerfile
    image: timhabermaas/cubemania_backup
    links:
      - db
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}

volumes:
  postgres-volume:
