version: "3.7"
services:
  db:
    image: postgres:9.5.3
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: timhabermaas/cubemania_nginx
    restart: always
    depends_on:
      - records
      - web
    ports:
      - "443:443"
      - "8080:80"
    volumes:
      - ./public:/home/assets
      # Replace ssl config with fake to prevent requiring certificates during
      # development.
      - ./nginx/empty_ssl.conf:/etc/nginx/ssl.conf
  records:
    build:
      context: ./records
      dockerfile: Dockerfile
    image: timhabermaas/cubemania_records
    restart: always
    environment:
      RUST_LOG: info
      RUST_BACKTRACE: 1
      HMAC_SECRET: someUnsecureSecret
      DATABASE_URL: postgresql://postgres@db/cubemania_production
    ports:
      - "8081:8081"
    depends_on:
      - db
  records-build:
    build:
      context: ./records
      dockerfile: Dockerfile
      target: builder
    depends_on:
      - db
    volumes:
      - ./records:/home/rust/src/records
  web:
    build: .
    image: timhabermaas/cubemania_rails
    restart: always
    command: bundle exec unicorn -p 3000 -c ./config/unicorn.rb
    volumes:
      - .:/cubemania
    ports:
      - "3000:3000"
    depends_on:
      - db
      - cache
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://postgres@db/cubemania_production
      HMAC_SECRET: someUnsecureSecret

  cache:
    image: memcached:alpine
    restart: always
    command: memcached -m 64

  backup:
    build:
      context: backup
      dockerfile: Dockerfile
    image: timhabermaas/cubemania_backup
    links:
      - db
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

volumes:
  postgres-volume:
