version: "3.7"
services:
  db:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "3"
  frontend:
    build:
      target: prod-runner
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "3"
  nginx:
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "443:443"
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "3"
    depends_on:
      - backup
  api:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "3"
  web:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "3"
  cache:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "3"
  backup:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50M"
        max-file: "3"
